name: Bump and Publish
on:
  release:
    types: [released]
jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 16
      
#       - name: 'Cache node Modules'
#         uses: actions/cache@v1
#         with:
#           path: ~.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-
#       - run: npm ci --ignore-scripts
#       - run: npm test
  bump-and-build:
#     needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: 'Cache node Modules'
        uses: actions/cache@v1
        with:
          path: ~.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: 'Install Dependencies'
        run: npm ci --ignore-scripts
      - name: 'Set version'
        run: npm --no-git-tag-version --allow-same-version version ${{ steps.get_version.outputs.VERSION }}
      - name: 'Prepare build'
        run: npm run prepare
      - name: 'Commit Bump to ${{ steps.get_version.outputs.VERSION }}'
      #          echo git config --local user.email "action@github.com"
#          echo git config --local user.name "GitHub Action"
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add package.json
          git add src/version.ts
          git status
          git commit -m "Bump to ${{ steps.get_version.outputs.VERSION }} [skip ci]"
          echo git push
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Release'
        run: npm run release-ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
